homepage/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.search, name='search'),
]

login/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'login'

urlpatterns = [
    path('', views.redirecting, name='redirect'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

story8/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('search-book/', include("homepage.urls")),
    path('', include("login.urls"))
]

homepage/models.py
from django.db import models

# Create your models here.

login/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.auth.decorators import login_required

def search(request):
    if request.method == 'GET':
        return render(request, 'search.html')
        
def redirecting(request):
    return redirect('/search-book/')

login/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            return redirect("homepage:search")

    else:
        form= AuthenticationForm()
    return render(request, "login.html", {'form':form})        
    
def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("login:login")
        
def redirecting(request):
    return redirect('/login/')

homepage/templates/search.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link id="pagestyle" rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'css/style.css'%}">
<script type = "text/javascript" src ="{% static 'js/index.js' %}"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
<title>Story 8 Ocit</title>

</head>

<body>
    {% if user.is_authenticated %}
        <h1 class="Sapa">Hai, {{ user.username }}</h1>
    {% endif %}
    <h1 class="Greetings">Cari buku disini</h1>
    {% if user.is_authenticated %}
        <form class="logout-link" action="{% url 'login:logout' %}" method="POST">
            {% csrf_token %}
            <button type="submit">Logout</button>
        </form>
    {% endif %}
    <div class="search-box">
        <div class="d-flex justify-content-center h-100">
            <div class="searchbar">
                <input class="search_input" type="text" name="" placeholder="Search...">
                <a href="#" class="search_icon"><i class="fas fa-search"></i></a>
            </div>
        </div>
    </div>  

    <table class="table table-striped table-bordered table">
            <thead class="thead-dark">
                <tr>
                    <th width = "20%" class="title text-center">Book Title</th>
                    <th width = "40%" class="desc text-center">Description</th>
                    <th width = "10%" class="link text-center">Author</th>
                    <th width = "30%" class="img text-center">Book Cover</th>
                </tr>
              
            </thead>

            <tbody>
            </tbody>
    </table>

</body>

</html>

login/templates/login.html
<!DOCTYPE html>
{% load static %}
<html>

<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="{% static 'css/styleLogin.css' %}">
<title>Story 8 Ocit</title>

</head>

<body> 
    <h1 class="Greetings">Halaman Login</h1>
    <div class="wrapper">
        
        <form class="site-form" action="{%url 'login:login'%}" method="post">
            {% csrf_token %}
            {{form}}
            <input class="login"type="submit" value="Login">
        </form>
    </div>
</body>

</html>